modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/raoulvdberge/rangedpumps"
[[mods]]
modId="rangedpumps"
version="${version}"
displayName="Ranged Pumps"
authors="Ranged Pumps contributors"
description='''
Ranged Pumps is a simple mod that adds a pump that pumps liquids in a range
'''
