modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/refinedmods/rangedpumps"
[[mods]]
modId="rangedpumps"
version="${version}"
displayName="Ranged Pumps"
updateJSONURL="https://refinedmods.com/ranged-pumps/update.json"
displayURL="https://refinedmods.com/ranged-pumps"
authors="Refined Mods"
description='''
Ranged Pumps is a simple mod that adds a pump that pumps liquids in a range
'''
